### ISSUE TITLE
Package Version Release Date

### ISSUE THREAD

**Issue by elanzini** [paulproteus/public-udd-mirror#15]
I am trying to get the release date for each version of a package but this information does not seem to be contained in the `packages` table.

Is this information available through UDD?

**Comment by mapreri** [comment]
you can find that in the upload_history table, but note that that's the Date field of the .changes, which is the date in the changelog. not always that's accurate.

**Comment by elanzini** [comment]
I was checking for package `openssl` but I noticed some versions did not appear in the `upload_history` table.

```
udd=> SELECT COUNT(*) FROM packages WHERE package='openssl';
 count 
-------
   111
(1 row)

udd=> SELECT COUNT(*) FROM upload_history WHERE source='openssl';
 count 
-------
   233
(1 row)
```

**Comment by mapreri** [comment]
the `packages` table is about binary packages available in the debian archive, through all suites/archs.  that means the `openssl` **binary** (not source package) times however many archs times however many current releases (adding -security, etc) there are.  See `select package, version, architecture, release from packages where package='openssl';` for more clarity.

What you likely want to *try* a best effort match to see when for example the current version of openssl that is currently in buster is:

```sql
udd=> select source, version, source_version, array_agg(architecture) from packages where package='openssl' and release='buster' group by version, source_version, source;
 source  |     version      |  source_version  |                             array_agg                             
---------+------------------+------------------+-------------------------------------------------------------------
 openssl | 1.1.1d-0+deb10u3 | 1.1.1d-0+deb10u3 | {amd64,arm64,armel,armhf,i386,mips,mips64el,mipsel,ppc64el,s390x}
(1 row)

-- and here you see how there is only one version AND it's the same as the source_version (which might not be true) AND what the source package name is.
-- then you can:

udd=> select date, changed_by, distribution from upload_history where source = 'openssl' and version = '1.1.1d-0+deb10u3';
 date | changed_by | distribution 
------+------------+--------------
(0 rows)
```

at which you realize that upload_history only records uploads in unstable and experimental and you are out of luck with direct uploads to anywhere else including buster.  If you wish to improve this part feel free to file a bug in the debian bug tracker rather than here.

But if you try other packages the best effort might produce better results, or if you try to match packages currently in unstable.
