### ISSUE TITLE
Provide time stamp of sync completion [was: Permission denied for relation bugs]

### ISSUE THREAD

**Issue by tautschnig** [paulproteus/public-udd-mirror#7]
Hi,

I'm not entirely sure what is going on here, but from time to time I keep getting "permission denied for relation bugs" errors, like this:

michael@l04[09:29]:~/Desktop$ date
Tue May 27 09:29:55 BST 2014
michael@l04[09:29]:~/Desktop$ psql --host=public-udd-mirror.xvm.mit.edu --user=public-udd-mirror udd --password
Password for user public-udd-mirror:
psql (9.1.9)
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
Type "help" for help.

udd=> SELECT id, bugs.source AS source FROM bugs INNER JOIN bugs_usertags USING (id) WHERE bugs_usertags.email = 'mt@debian.org' AND bugs_usertags.tag = 'goto-cc' AND source='sopwith' ORDER BY source;
ERROR:  permission denied for relation bugs
udd=> \q

I just confirmed that the UDD instance on ullmann.d.o does not have this issue:
mt@ullmann:~$ psql service=udd
psql (9.1.13)
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
Type "help" for help.

udd=> SELECT id, bugs.source AS source FROM bugs INNER JOIN bugs_usertags USING (id) WHERE bugs_usertags.email = 'mt@debian.org' AND bugs_usertags.tag = 'goto-cc' AND source='sopwith' ORDER BY source;
   id   | source
--------+---------
 748172 | sopwith
(1 row)

Am I doing something wrong?

Best,
Michael

**Comment by paulproteus** [comment]
Thanks for filing this!

As for the permissions issue -- this is something I need to fix in my scripts. I'll do that.

As for the timing issue, I wonder what is the best way to deal with this is. Perhaps I should "just" disable Postgres access during the import, and then re-enable it after the import, so that if the service is available, it's always consistent? That's a bit hacky, I realize. A different thing I could do is import into a temp database name and then rename it per http://www.postgresql.org/docs/9.1/static/sql-alterdatabase.html

**Comment by tautschnig** [comment]
Unless you face RAM/disk memory limitations, doing the database rename sounds like a nice idea to reduce the downtime. Obviously there's still a non-0 possibility of catching the missing database when it has been dropped but not yet renamed, but this window should be reasonably small I guess.

Thanks a lot for all your work on this!

**Comment by mapreri** [comment]
It has been a while since we import in a database and then do the drop&rename dance.
If you face others issues, please open a new bug.
